name: Publish Static Content
run-name: Publish Static Content
on:
  push:
    branches:
      - main
jobs:
  Publish-Static-Content:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Configuring build environment."
      - run: sudo apt-get update && sudo apt-get install -y python3 python3-pip && sudo apt-get clean
      - run: pip3 install mkdocs
      - run: pip3 install mkdocs-material
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Building site"
      - run: cd ${{ github.workspace }}
      - run: mkdocs gh-deploy --force
      - run: echo "🍏 This job's status is ${{ job.status }}."
